### PR TITLE
Update gulp-util

### PR DESCRIPTION
**Pull request by josephpage**
From 2.x.x to 3.x.x
No breaking changes mentionned : https://github.com/gulpjs/gulp-util/releases

### CODE REVIEW

**Comment by Kagami** [comment]
Are there any particular reasons for the bump? I'm not against that change, just curious.

**Comment by Kagami** [comment]
It seems to be safe to update indeed:
https://github.com/gulpjs/gulp-util/pull/58#issuecomment-49530774

**Comment by josephpage** [comment]
Hello @Kagami
Thanks for reviewing.

I use `npm dedupe` to save spaces on our dev environment, I got that : 

```
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict gulp-util { '/app/node_modules/gulp-concat-css/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-concat/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-connect/node_modules/gulp-util': '2.2.20',
npm WARN unavoidable conflict   '/app/node_modules/gulp-footer/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-eslint/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-header/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-inject/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-jade/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-ng-config/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-ng-annotate/node_modules/gulp-util': '2.2.20',
npm WARN unavoidable conflict   '/app/node_modules/gulp-stylus/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp-uglify/node_modules/gulp-util': '3.0.6',
npm WARN unavoidable conflict   '/app/node_modules/gulp/node_modules/gulp-util': '3.0.6' }
```

Seems that gulp-util is globally used by gulp plugins, gulp-ng-annotate should too. Furthermore, its size is 2 MB, so deduping it would be a good deal.
(see also AveVlad/gulp-connect#137 for the other conflict)

**Comment by Kagami** [comment]
Seems legit. Thanks!

**Comment by josephpage** [comment]
Thanks !

**Pull request merged**
