### PR TITLE
Default options

### LINKED ISSUE #17: add is set to false if options provided
`add` option should be `true` by default, and shouldn't change if another option like `rename` is set, unless `add` is explicitly set to `false`.

### PR DESCRIPTION
**Pull request by andreicojea**
Fixes #17

### CODE REVIEW

**Comment by Kagami** [comment]
I was faster :)

**Comment by andreicojea** [comment]
But you're not consistent with the original plugin api :P

You should be able to use booth `--add` and `--remove` simultaneously:

> "... use --add --remove (-ar) to rebuild all annotations)" https://github.com/olov/ng-annotate#installation-and-usage)

**Comment by andreicojea** [comment]
I think extending a default options object is preferable, you may end up having more defaults in the future.

**Comment by Kagami** [comment]
I'm using `merge` exactly for that. `merge({add: true}, {add: false, sourcemap: true}) == {add: false, sourcemap: true}`. If user passed `{remove: true}` than the options will be `remove: true`. If user passed `{add: true, remove: true}` then the options would be `{add: true, remove: true}`.
Am I missing something?

**Comment by andreicojea** [comment]
options = options || {};
       if (!options.remove) {
        options = merge({add: true}, options);
      };

what if options is `{remove: true, rename: [{from:"sth", to:"something"}]}`?

**Comment by Kagami** [comment]
Then the options object should be untouched, shouldn't it?

**Comment by andreicojea** [comment]
No, should have `add: true` by default.

**Comment by Kagami** [comment]
Why should it imply add=true even if user specified remove=true? In my opinion that would be nonintuitive.

See here: https://github.com/olov/ng-annotate/blob/master/ng-annotate-main.js#L947
Basically `ng-annotate` has 3 modes: add, remove and rebuild. By default `gulp-ng-annotate` will use add mode, but it's up to the user to choice remove or rebuild mode by passing `{remove: true}` or `{remove: true, add: true}` respectfully.

**Comment by andreicojea** [comment]
Actually, I think you're kinda right, but I equally unintuitive to have one default value changed by another default, especially when they can coexist. I noticed you updated the docs too, should be fine now :-)

**Comment by Kagami** [comment]
Yea, it's hard to be intuitive for everyone.

**Comment by andreicojea** [comment]
Anyways, thanks for help! This plugin is awesome :+1:

**Pull request closed without merging**
